language: node_js

node_js:
    - '12'
install:
    - npm install
script:
    - npm run build

deploy:
    provider: pages
    local-dir: build
    skip-cleanup: true
    keep-history: true
    fqdn: dimastark.ru
    github-token: $GITHUB_TOKEN
    on:
        branch: master
